[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/health-privacy-request"
  to = "/privacy-request.html"
  status = 200

[[redirects]]
  from = "/health-privacy-policy"
  to = "/privacy-policy.html"
  status = 200
